# Generated by Django 2.2.6 on 2019-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191008_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
