# Generated by Django 2.2.6 on 2019-10-09 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0003_student_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['teacher', 'start_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['teacher', 'name']},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('is_new', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher', '-is_new', 'due_at'],
            },
        ),
    ]
