# Generated by Django 2.2.6 on 2019-10-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_lesson_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lesson_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lesson_weekday',
        ),
    ]
