# Generated by Django 2.2.6 on 2019-10-14 17:20

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20191014_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['teacher', django.db.models.functions.text.Lower('name')]},
        ),
    ]
