# Generated by Django 2.2.6 on 2019-10-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20191014_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['teacher']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_at',
        ),
    ]
