# Generated by Django 2.2.6 on 2019-10-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20191014_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['teacher', 'start_time']},
        ),
    ]
