# Generated by Django 2.2.6 on 2019-10-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20191014_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['teacher', 'day', 'start_time']},
        ),
    ]
