# Generated by Django 2.2.6 on 2019-10-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20191015_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['teacher', 'start_at']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
    ]
